---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      version: '6.1.6'
      sourceRef:
        kind: HelmRepository
        name: podinfo
  releaseName: podinfo
  interval: 10m0s
