---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web-service
spec:
  chart:
    spec:
      chart: nginx
      version: '13.1.5'
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m0s
